@baseUrl = http://localhost:3001/api

# Current user ################################################

# @name getCareer
GET {{baseUrl}}/portfolio/career

###

# @name getGallery
GET {{baseUrl}}/portfolio/gallery

###

# @name getAngularEvents
GET {{baseUrl}}/angular-sandbox/events

###

# @name getAngularRecipes
GET {{baseUrl}}/angular-sandbox/recipes

###